# Inverse of a Matrix using Numpy

The inverse of a matrix is just a reciprocal of the matrix as we do in normal arithmetic for a single number which is used to solve the equations to find the value of unknown variables. The inverse of a matrix is that matrix which when multiplied with the original matrix will give as an identity matrix. The inverse of a matrix exists only if the matrix is non-singular i.e., determinant should not be 0. Using determinant and adjoint, we can easily find the inverse of a square matrix using below formula,

if det(A) != 0
    A-1 = adj(A)/det(A)
else
    "Inverse doesn't exist" 


Inverse of a Matrix using NumPy
Python provides a very easy method to calculate the inverse of a matrix. The function numpy.linalg.inv() which is available in the python NumPy module is used to compute the inverse of a matrix. 

In [3]:
# Import required package
import numpy as np

In [4]:
# Taking a 3 * 3 matrix
A = np.array([[4, 3, 6],
              [2, 5, 9],
              [8, 6, 3]])


In [5]:
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.30952381 -0.21428571  0.02380952]
 [-0.52380952  0.28571429  0.19047619]
 [ 0.22222222  0.         -0.11111111]]
